version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw test 
  post_build:
    commands:
      - echo Build completed on `date`
      - ./mvnw package
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
